soundsolution/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.MainPage.as_view(),name='main-page'),
    #path('bithday/',views.BirthdayPage.as_view(),name='birthday-page'),
]

soundsolution/soundsolution/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls',namespace='main'))
]

soundsolution/main/models.py
from django.db import models

# Create your models here.

soundsolution/main/views.py
from random import choice
from typing import Any
from django.views.generic import TemplateView

class MainPage(TemplateView):
    template_name = 'index.html'
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        context['message'] = choice(["Звуки, которые создают впечатление!",
                                    "Ваше мероприятие — наше искусство.",
                                    "Ваше мероприятие - задача, мы - решение.",
                                    "Мы создаем атмосферу, которая оставит вас в восторге.",
                                    "Ваш путь к моментам, которые запоминаются навсегда.",
                                    "Ваш партнер в организации событий."])
        
        context["weddings"] = choice(["Сделайте свою свадьбу незабываемой с нами!",
                                    "Ваша сказочная свадьба начинается здесь.",
                                    "Любовь, счастье, моменты – вместе с нами."])

        context["corporate_events"] = choice(["Усиление команды через развлечение.",
                                    "Преобразите свой бизнес-митинг в событие для запоминания.",
                                    "Вдохновение и инновации начинаются с нас."])
        context["birthdays"] = choice(["Пусть каждый год будет лучше предыдущего.",
                                    "Создайте воспоминания, которые будут с вами всегда."])
        context["concerts"] = choice(["Музыка – это жизнь, и мы делаем ее лучше.",
                                    "Ваши любимые артисты, ваше незабываемое впечатление."])
        return context

class BirthdayPage(TemplateView):
    template_name = "birthday.html"

soundsolution/main/templates/main/contacts.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Контакты
{% endblock title %}
{% block body %}
<div class = 'text-center mt-5'>
<h3>
Телефоны: <br>
+375 232 29-16-93 (Городской)<br>
+375 447 51-15-89 (Life)
</h3>
</div>
<div class = 'text-center mt-5'>
<h3>Адрес: <br>
Гомельская область, г. Гомель, ул. Оршанская, 20
</h3>
<br>
<h3>Почтовый адрес: <br>
246039
г. Гомель,
ул. Весенняя,
174А
</h3>
</div>
<h4>
<div class = 'text-center mt-5'>
<a href='https://yandex.by/maps/155/gomel/house/Z0kYfwZkS0cAQFtofXhyd3tmZQ==/?ll=30.914227%2C52.436751&z=16.69'>Найти нас на карте</a>
</h4>
</div>
{% endblock body %}

soundsolution/templates/base.html
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang='en'>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
    {% block title %}
    {% endblock title %}
    </title>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'main:main-page' %}">
            <img src="{% static 'main/logo.png' %}" alt="Logo" width="200" height="72" class="d-inline-block align-text-top"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'main:contacts' %}"  style="font-size: 23px;">Контакты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:about' %}" style="font-size: 23px;">О нас</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>
    <body>
    {% block body %}
    {% endblock body %}
    </body>
</html>

soundsolution/templates/navbar.html
  {% load static%}
  <header id="header-section">
    <nav class="navbar navbar-expand-lg pl-3 pl-sm-0" id="navbar">
    <div class="container">
      <div class="navbar-brand-wrapper d-flex w-100">
        <img src="{% static 'assets/images/black_logo.png' %}" alt="" style="max-width: 150px; max-height: 150px;">
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="mdi mdi-menu navbar-toggler-icon"></span>
        </button> 
      </div>
      <div class="collapse navbar-collapse navbar-menu-wrapper" id="navbarSupportedContent">
        <ul class="navbar-nav align-items-lg-center align-items-start ml-auto">
          <li class="d-flex align-items-center justify-content-between pl-4 pl-lg-0">
            <div class="navbar-collapse-logo">
              <img src="{% static 'assets/images/black_logo.png' %}" alt="" style="max-width: 150px; max-height: 150px;">
            </div>
            <button class="navbar-toggler close-button" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="mdi mdi-close navbar-toggler-icon pl-5"></span>
            </button>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#header-section" style="white-space: nowrap; font-size: 18px;">Главная <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#features-section" style="white-space: nowrap; font-size: 18px;">Почему мы ?</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#digital-marketing-section" style="white-space: nowrap; font-size: 18px;">О нас</a>  
          </li>
          <!--<li class="nav-item">
            <a class="nav-link" href="#feedback-section" style="white-space: nowrap; font-size: 18px;">Услуги</a>
          </li> -->
          <li class="nav-item btn-contact-us pl-4 pl-lg-0">
            <button class="btn btn-info" data-toggle="modal" data-target="#exampleModal" style = "font-size: 15px;">Связаться с нами</button>
          </li>
        </ul>
      </div>
    </div> 
    </nav>   
  </header>

soundsolution/templates/slogan.html
  {% load static %}
  <div class="banner" >
    <div class="container">
      <h1 class="font-weight-semibold">{{message}}</h1>
      <h6 class="font-weight-normal text-muted pb-3">- Sound Solution</h6>
      <img src="{% static 'assets/images/Group171.svg' %}" alt="" class="img-fluid">
    </div>
  </div>